### ISSUE TITLE
Bug related to PATH 

### ISSUE THREAD

**Issue by Phant0m-a** [Plasmonix/Youtube-viewbot#10]
snippet of error

`
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ahsan Ali\Desktop\Youtube-viewbot\main.py", line 93, in <module>
    n.main()
  File "C:\Users\Ahsan Ali\Desktop\Youtube-viewbot\main.py", line 89, in main    
    self.open_url(self.ua, self.sleeptime, proxy)
  File "C:\Users\Ahsan Ali\Desktop\Youtube-viewbot\main.py", line 57, in open_url   
    driver = webdriver.Chrome(options=options)
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
`

- it says chromdriver executable needs to be in PATH, fun fact = 2 days ago i deleted my PATH variable  and it was messing up lots of stuff ... maybe thats why i got this error

**Comment by Phant0m-a** [comment]
never mind i found the line in main.py where it says to uncomment the line ...😊thanks
